### ISSUE TITLE
Strict variable access

### ISSUE THREAD

**Issue by srid** [sebastienros/fluid#295] opened 2021-03-30 05:15 UTC
Right now, if you refer to `{{ Foo.Bar }}` in the template and if "Bar" doesn't exist in "Foo", then an empty string will be used in its place. Is it possible to change the library to ... have the render function just error out in this case? 

The goal is to have as type-safe of a template / var system as possible, when generating the static site, so that accidentally missing vars don't end up generating invalid sites without the user being made aware of it (unless they are extremely careful to vet the generated HTML each time).

**Comment by sebastienros** [comment] 2021-03-31 16:38
Creating a tag for error messages. I will probably add this behavior as an option. Some people might prefer to not break a page instead. But then you might want to set it per the environment, like enabled in prod and disabled in dev.

**Comment by sebastienros** [comment] 2021-05-03 00:15
Duplicate of https://github.com/sebastienros/fluid/issues/64

**Closed by sebastienros** 2021-05-03 00:15 UTC
Labels: error_message
