### ISSUE TITLE
Default registration ALL dto / models

### ISSUE THREAD

**Issue by weedkiller** [sebastienros/fluid#452] opened 2022-01-10 00:28 UTC
Hello I think this is a great idea. It takes a very long time to register each and every model on production systems with fluid.

Please consider an option such that it, would be a much easier for developers to use; if you had a `default option to register all the DTO, VeiwModels or models in a folder or during on model creating` to allow them to be exposed to the fluid liquid template.

Or at least can you show us an option to register everything in a folder or in a namespace in one line of code/configuration.

**Comment by sebastienros** [comment] 2022-01-10 03:06
Duplicate of #388

**Closed by sebastienros** 2022-01-10 03:06 UTC
